# Generated by Django 5.1 on 2024-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_office_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
